# Generated by Django 4.2 on 2023-04-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_company_project_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="company",
        ),
        migrations.AddField(
            model_name="project",
            name="tasks_completed",
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="Company",
        ),
    ]
