# Generated by Django 4.2 on 2023-04-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "projects",
            "0003_remove_project_company_project_tasks_completed_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="tasks_completed",
            field=models.IntegerField(),
        ),
    ]
