# Generated by Django 4.2 on 2023-04-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_task_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
