# Generated by Django 4.2 on 2023-04-27 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0006_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="new_notes",
                to="tasks.task",
            ),
        ),
    ]
