# Generated by Django 4.2 on 2023-04-27 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0007_alter_note_task"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="text",
            new_name="notes",
        ),
        migrations.AlterField(
            model_name="note",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_note",
                to="tasks.task",
            ),
        ),
    ]
